### ISSUE TITLE
Initiative Card: The initiative name appears in Arabic in the English UI and vice versa

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#1]
Steps:
1- login to the system (epmadmin, Master@123)
http://rmpplus-qc.masterteam.sa/#/programs-card
Actual result: 
The initiative name appears in Arabic in the English UI and vice versa
![image](https://user-images.githubusercontent.com/107788214/193443004-667a6d3e-6877-4f40-86e3-44773ce0db75.png)

![image](https://user-images.githubusercontent.com/107788214/193443092-950b507c-eae1-4a20-bedb-205d3ca98956.png)

Expected result: 
The initiative name should appear in English in the English UI and vice versa
![image](https://user-images.githubusercontent.com/107788214/193443043-98ba90dc-5983-44b5-887e-05b6e0293d0f.png)

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/193443608-877b171a-a5eb-4799-99e9-46f360c1b8ae.png)

**Comment by JarrarMo** [comment]
@hebaabutaha same applies on project level.

**Comment by JarrarMo** [comment]
@KhaldounAl-haj kindly confirm.

**Comment by KhaldounAl-haj** [comment]
Confirmed
