### ISSUE TITLE
Create New Project: when check the "Operational?" checkbox, let the initiative name appear "Operational Initiative"

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#10]
![image](https://user-images.githubusercontent.com/110157969/193450507-48793b2e-32ab-40a8-874e-69afa93c3003.png)

**Comment by JarrarMo** [comment]
@DemaHamideh This was made as per requirements.
@KhaldounAl-haj kindly confirm.

**Comment by KhaldounAl-haj** [comment]
@DemaHamideh the business will stay the same when the user choses the operational checkbox the system will disable the initiative DDL and will add the project to the "operational initiative container"

**Comment by DemaHamideh** [comment]
Closed as per Khaldon's feedback
