### ISSUE TITLE
Project edit page : The system should display the label " Rejection reason" instead of "comment" when user click on reject button on his request 

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#100]
Steps: 
1.Login using Epmadmin/Master@123
2.Click on task center button on the header
3.Click on pending request on the PMO processes section
4.Click on reject button

Actual: ![image](https://github.com/user-attachments/assets/973f4d75-204d-4738-bbdb-8f33a76ec732)
Expected: 
![image](https://github.com/user-attachments/assets/cb543eda-7b07-4d48-87d9-d05388f459b7)

**Comment by nadeemyaldani** [comment]
Just change labal please @SamerElaila

**Comment by rhamad4** [comment]
![image](https://github.com/user-attachments/assets/86af2414-740b-4cbd-9577-4844e7e89018)

fixed
