### ISSUE TITLE
Initiatives and Projects Dashboard : If the user selects more than one initiative on initiatives filter , the achievements of the last selected initiative will be displayed

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#103]
Steps: 
1.Login to the system
2.Click on "Initiatives and Projects Dashboard" button
3.Select more than one initiatve on initiative filter
4.check the value on "Key achievements of initiatives" section

![image](https://github.com/user-attachments/assets/68b5f90c-c38d-4bc0-9f3b-d46b70a8dde4)
![image](https://github.com/user-attachments/assets/08e35013-9820-4f50-a566-e6bb6b192a21)

**Comment by nadeemyaldani** [comment]
@tareqissa This feel wrong, we have multiple initiatives and each have it's own Achievements, 
showing the Achievement for  the last one in the filter list  does not make sense.
![image](https://github.com/user-attachments/assets/53ab8b2f-359e-4c9c-a2a4-1eee06db8c61)

**Comment by nadeemyaldani** [comment]
@JarrarMo Please advice

**Comment by JarrarMo** [comment]
As confirmed by @tareqissa 
- No selection will not show anything
- For each selected initiative we will show achievements in table

@tareqissa said he will provide a simple design idea and consider the vertical scroll.

@nadeemyaldani kindly work on it from BE if needed.

**Comment by nadeemyaldani** [comment]
@SamerElaila make it so the component is hidden when there is no Initiatives selected in Filter for now, we will receive a sketch for it soon

**Comment by rhamad4** [comment]
![image](https://github.com/user-attachments/assets/73a411af-1165-43bb-aa78-06786348e6f8)
