### ISSUE TITLE
Initiatives and Projects Dashboard : The "Projects by Status" chart , finish date value is wrong

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#104]
Steps:
1.Login to the system
2.Click on "Initiatives and Projects Dashboard" button
3.Click on details button on the "Projects by Status" chart
4.Check the finish date

Actual: 
![image](https://github.com/user-attachments/assets/f626f4b3-6760-4b8c-8de2-5c6f863e281b)

Expected: ![image](https://github.com/user-attachments/assets/4b4a73be-12b6-4fda-87e2-bb50af1293ea)

**Comment by nadeemyaldani** [comment]
@SamerElaila Map to these 
![image](https://github.com/user-attachments/assets/eebb7970-b50b-4990-8575-74268c8ad922)

**Comment by rhamad4** [comment]
![image](https://github.com/user-attachments/assets/63f5f228-567f-48a1-9555-f0a401ac45c7)
fixed
