### ISSUE TITLE
Initiatives and Projects Dashboard : The system should display only the active risks impacts on the "Risks by Impact" chart

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#105]
Steps:
1.Login to the system
2.Click on "Initiatives and Projects Dashboard" button
3.Check the legends on the "Risks by Impact" chart

Actual : 
![image](https://github.com/user-attachments/assets/17a3db11-cb94-4202-8d79-240064ec5fea)

Expected: 
![image](https://github.com/user-attachments/assets/5839ac83-7a21-4a28-8b98-d0226afa0a44)

**Comment by nadeemyaldani** [comment]
![image](https://github.com/user-attachments/assets/c43a7635-5f71-42a4-bb59-f22ff6f35a9d)
![image](https://github.com/user-attachments/assets/c83f3cf8-d818-4184-9671-76924c5de06b)

**Comment by rhamad4** [comment]
![image](https://github.com/user-attachments/assets/63dbc7e1-4517-4c00-ae18-37da80035b6a)
fixed
