### ISSUE TITLE
Project Card: Planned progress value is not correct 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#11]
Steps:

1. login as epmadmin/Master@123
2. click ديمة تيست
3. click on Dema project test

Actual Result: 
Planned is -100 

![image](https://user-images.githubusercontent.com/110157969/193450866-bacbebd6-dd62-4741-83bf-a512ec0d04f0.png)

![image](https://user-images.githubusercontent.com/110157969/193450878-0693b611-7697-4228-8636-2324fb3c92c1.png)

**Comment by DemaHamideh** [comment]
other scenarios appears recently: 

1. Dema1234 Project    http://rmpplus-qc.masterteam.sa/#/project/72a711b4-9f07-4a00-81f7-db26a9264498/preview

![Dema1234_1](https://user-images.githubusercontent.com/110157969/193551557-0a8b8288-367d-416b-98c0-49d6091a508c.png)


![Dema1234_2](https://user-images.githubusercontent.com/110157969/193551582-d063d2cf-63f5-46ae-9c69-0bbedee2c11f.png)

2. test planned Project http://rmpplus-qc.masterteam.sa/#/project/14eb5756-ee6c-46dd-802e-325c79a710de/preview

![testplanned_1](https://user-images.githubusercontent.com/110157969/193551787-648ca4bb-010e-474d-a7e8-1e9343708008.png)


![image](https://user-images.githubusercontent.com/110157969/193551851-6b388280-4eba-45a3-be93-e3389eb38d87.png)


3. test999 Project http://rmpplus-qc.masterteam.sa/#/project/c6b97172-864b-47bc-a590-9aafaf23c320/preview

![image](https://user-images.githubusercontent.com/110157969/193552889-75d5d9f8-8825-4a9b-8e9a-6d220634ae59.png)


![image](https://user-images.githubusercontent.com/110157969/193552960-dd0b62d4-a91c-4608-907a-c3f3119fabd2.png)

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/194097949-48a1fc22-efcc-425d-a09a-b1dc5440c286.png)

**Comment by DemaHamideh** [comment]
Pass 

![image](https://user-images.githubusercontent.com/110157969/194254880-500469aa-b676-4d2d-953f-0eb2b8999425.png)


![image](https://user-images.githubusercontent.com/110157969/194254734-dbf69b9c-841e-43be-85ab-b0b3e211f492.png)
