### ISSUE TITLE
Initiatives and Projects Dashboard: On the "Projects by Status" chart, the Achievements column is missing

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#110]
Steps:
1.Login to the system
2.Click on "Initiatives and Projects Dashboard" button
3.Choose "RH project 1" from project filter
4.Click on the Details button on the "Projects by Status" chart
5.Check the column names

Actual : Achievements column is missing
Expected: system display the Achievements column
![image](https://github.com/user-attachments/assets/85b9bca5-ab7e-407d-b408-3fb1d544162b)

**Comment by nadeemyaldani** [comment]
As per the release notes Email  this is a BRD mistake 
![image](https://github.com/user-attachments/assets/c8a8180f-b76a-43c9-95ac-e81f45ff8278)
