### ISSUE TITLE
Initiatives and Projects Dashboard : translate the entities to arabic in arabic system on the "Distribution of Projects Status by Entity" chart

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#112]
Steps:
1.Login to the system
2.Click on "Initiatives and Projects Dashboard" button
3.Change the language to arabic 
4.Check the "Distribution of Projects Status by Entity" chart

![image](https://github.com/user-attachments/assets/0c9807e1-5998-4590-bb88-ecdfaa7dca10)

**Comment by nadeemyaldani** [comment]
![image](https://github.com/user-attachments/assets/1baf32cf-a0d3-4645-9a89-8a10408497d7)

**Comment by rhamad4** [comment]
![image](https://github.com/user-attachments/assets/41d3c080-6974-4246-a97d-0cc4da81ab2d)

fixed
