### ISSUE TITLE
Initiatives Page : the initiative status is wrong

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#113]
Steps:
1.Login to the system
2.Click on "Initiatives " tab
3.Check the "Rh Initiatieve 2" status

Actual : ![image](https://github.com/user-attachments/assets/d7d6b604-7469-4f86-ad38-b83103ce156d)
Expected: 
![image](https://github.com/user-attachments/assets/45414984-4ca1-4691-9800-dbfc3764a1f0)

**Comment by nadeemyaldani** [comment]
@AhmedShaabanX Use this handshake for the statuses and Legends
PPlusHandshakes
![image](https://github.com/user-attachments/assets/c7a5aa25-b51c-41cb-aeb6-5a8924d1c386)

**Comment by rhamad4** [comment]
fixed
![image](https://github.com/user-attachments/assets/2fba6cc3-4d22-43e3-a37d-d330a1669c6b)
