### ISSUE TITLE
Strategic objective calculation has something wrong from the KPI side

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#116]
![image](https://github.com/user-attachments/assets/e124e5b5-7eca-44ad-bfdc-b517d71f15cd)
![image](https://github.com/user-attachments/assets/f80247e3-18fb-4222-9be3-9d640c959906)

**Comment by nadeemyaldani** [comment]
As Agreed with @tareqissa We will consider the KPI Target as 100% in the Planned calculation 
by this we will convert both  Actual and planned to Percentages

**Comment by tareqissa** [comment]
@nadeemyaldani 
confirmed

**Comment by rhamad4** [comment]
fixed
