### ISSUE TITLE
Project Workspace - Overview Tab: texts needs to be modified 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#12]
![image](https://user-images.githubusercontent.com/110157969/193451708-6deda4c4-40e1-4a02-a969-c00e515555e5.png)

![image](https://user-images.githubusercontent.com/110157969/193451731-825a61b4-cc4b-466d-b803-058260cbe77e.png)

**Comment by ealtiti** [comment]
fixed
<img width="1408" alt="Screen Shot 2022-10-04 at 10 56 52 AM" src="https://user-images.githubusercontent.com/85454412/193765738-0bf18331-c5b0-4911-89b8-8a0e40a90ec3.png">
<img width="1408" alt="Screen Shot 2022-10-04 at 10 56 45 AM" src="https://user-images.githubusercontent.com/85454412/193765720-3de3ed0c-084e-419a-a998-2275f186453d.png">
