### ISSUE TITLE
KPIs dashboard : Translate the Entites name to arabic at the "Distribution of KPIs Status by Entity" chart

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#121]
![image](https://github.com/user-attachments/assets/f9027bec-3c81-4840-8775-4faf21feb0a8)

**Comment by nadeemyaldani** [comment]
Take the entity name from PPlusHandshakes service, and the look up name is "ProjectParties"

**Comment by rhamad4** [comment]
![image](https://github.com/user-attachments/assets/e88e73e9-03c8-4dba-bc52-a56ea736aeb6)
fixed
