### ISSUE TITLE
Executive Dashboard : The objective filter was not mentioned in the BRD or the design

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#122]
Actual: ![image](https://github.com/user-attachments/assets/4d5bd8c7-0845-4f89-8e16-dede2a8586ec)

BRD: 
![image](https://github.com/user-attachments/assets/38fdd3a2-7eea-4155-a587-0150c043d51e)

Design : 
![image](https://github.com/user-attachments/assets/9d7c4c75-f69c-4cb2-a490-a6fb1b73abeb)

**Comment by nadeemyaldani** [comment]
Invalid, the S+ is made to handle multiple strategy making the dashboard for one strategy as static, will cause issues in the future 
this was discussed and approved by @tareqissa

**Comment by tareqissa** [comment]
@rhamad4 
this is not objective filter, this is Strategy filter and as @nadeemyaldani said, the system is allowed to create multiple strategies so we preferred to have this filter to support viewing all strategies created in the system.
