### ISSUE TITLE
Executive Dashboard : system does not display the cancelled project on the "Projects Execution by Status" chart

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#123]
Steps: 
1.Login using master_champion
2.Open the " http://rmsplus-qc.masterteam.sa/#/splus/executives-performance-dashboard " link
3.Select "Municipality Strategy " strategy
4.Click on details button on the "Projects Execution by Status" chart
5.check the status of the RH project 1

![image](https://github.com/user-attachments/assets/2aff6bfc-a55f-4322-aa3f-228afd374a1d)

![image](https://github.com/user-attachments/assets/8e909898-1da8-4181-b44b-d63f086f13f4)

**Comment by nadeemyaldani** [comment]
![image](https://github.com/user-attachments/assets/e12841b4-c463-4523-934c-1792d6f69d38)
for Projects Use this to read also change the legends
![image](https://github.com/user-attachments/assets/51b2cdaf-de27-40fb-853d-5f72c5c9a04b)

**Comment by rhamad4** [comment]
![image](https://github.com/user-attachments/assets/f5497730-57af-45a4-91d6-172c88969f18)
fixed
