### ISSUE TITLE
Strategy page : Is it correct that the pillar progress = Average of strategic objective's taregt ?

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#124]
![image](https://github.com/user-attachments/assets/78ad525e-f640-4495-94e5-c61d075ec940)

**Comment by nadeemyaldani** [comment]
We show Performance by Calculating the Average of the Actual Progress of the Objectives, i think this is a BRD issue

**Comment by tareqissa** [comment]
@rhamad4 
as @nadeemyaldani said, I believe it's typo, it should be the actual value not the target
