### ISSUE TITLE
Executives dashboard : There is issue with "Initiatives Execution by Status" chart

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#125]
Steps: 
1.Login using master_champion
2.Open the " http://rmsplus-qc.masterteam.sa/#/splus/executives-performance-dashboard " link
3.Select "Municipality Strategy " strategy
4.Select " Compliance and Environmental Sustainability Agency " entity from entity filter
5.Select orange status from "KPIs by Status" chart
6.check number of initiatives on the "Initiatives Execution by Status" chart

Actual : 
![image](https://github.com/user-attachments/assets/1540bbd4-ac1f-4805-b048-0bab74cd98fb)

Expected: 
![image](https://github.com/user-attachments/assets/133c1312-8749-4e09-a438-01f06d68d1b2)

**Comment by AhmedShaabanX** [comment]
![Screenshot 2024-07-31 184819](https://github.com/user-attachments/assets/1cc1c761-a8a7-449e-aa3e-7ec3f5c1ae25)
just shown what i get from BE service ..
