### ISSUE TITLE
Deliverables page on project workspace: System should display the Risk name When hoovering over the risk name on the delivrables table and navigate the user to risk page once clicking on the Risk icon

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#128]
Steps:
1.Login to the system ( tsalah )
2.Open "https://epmostg.alriyadh.gov.sa/#/project/751230ed-d76d-4fe3-b487-6bfcd5df0f0a/deliverables" link
3.Hoover over the Risk icon
4.Click on Risk icon

Actual: nothing happend once hoover over the risk icon and click on it

![image](https://github.com/user-attachments/assets/5f81e5a1-8af4-43d3-b414-ede49358849e)

**Comment by nadeemyaldani** [comment]
@JarrarMo @SamerElaila 
This need investigation on QC,

**Comment by JarrarMo** [comment]
@SamerElaila as agreed, kindly contact @rhamad4 tomorrow to see it on staging.

**Comment by rhamad4** [comment]
Passed on QC

**Comment by rhamad4** [comment]
checked on Stag and paased
