### ISSUE TITLE
Project edit feature : System will not display all names drop down lists values on edit form

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#129]
Steps:
1.Login using tsalah
2.Open "https://epmostg.alriyadh.gov.sa/#/project/0b1015a8-86b3-46ec-9312-d2c6922290ed/preview" link
3.Click on edit button
4.Check the availability of the project sponsor and owner

![image](https://github.com/user-attachments/assets/ce3d1b7b-aa14-4b5c-bbb7-9fbfe374cdbe)
![image](https://github.com/user-attachments/assets/a0091409-642d-43d6-a6b5-f08637b3b5ad)

**Comment by rhamad4** [comment]
I did

**Comment by nadeemyaldani** [comment]
I need it to be at least reproduced on QC, to be able to check what's wrong @rhamad4

**Comment by rhamad4** [comment]
![image](https://github.com/user-attachments/assets/2767256c-8958-4a75-8113-59c70c2c8c29)
passed on stag
