### ISSUE TITLE
Project Workspace - Phase Gate Tab: the PMO can approve/reject the request from task center only but when click on the request, the shown page will not contains approve/reject buttons

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#13]
https://user-images.githubusercontent.com/110157969/193452803-cc1b0ca2-4d35-4af1-82d1-c6ac93c53d26.mp4

**Comment by DemaHamideh** [comment]
@JarrarMo 
kindly note that this appears for users that do not have admin permission (have PMO Group permission), but the buttons appear successfully for users that have admin permission.

**Comment by ealtiti** [comment]
This not FE OR BE its Support team cus missing key at config js

**Comment by ealtiti** [comment]
<img width="1428" alt="Screen Shot 2022-10-04 at 11 17 17 AM" src="https://user-images.githubusercontent.com/85454412/193769849-38517089-a585-4a7d-94ec-ded82781f14d.png">
<img width="1428" alt="Screen Shot 2022-10-04 at 11 17 25 AM" src="https://user-images.githubusercontent.com/85454412/193769866-f8554b5d-caac-479f-87fe-d8e9f7c7d7b2.png">

**Comment by DemaHamideh** [comment]
Pass

![image](https://user-images.githubusercontent.com/110157969/193798494-43acb841-4296-4497-af3b-f1c892c0dbd0.png)
