### ISSUE TITLE
Project edit feature: system does not display the user Role on task center 

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#130]
Steps:
1.Login using rhamad/P@ssw0rd
2.Click on task center button on the header
3.Click on 'RH project ar 1" lable on the PMO processes chart
4.Check the action history table

Actual: system does not display the Role 
Expected: system should display the Role of the user ( project manager or PMO admin )

**Comment by nadeemyaldani** [comment]
Role will show for Groups Like PMO group on requests and not the manager, 
this is per our discussion with @tareqissa 
![image](https://github.com/user-attachments/assets/79f99140-70bd-4ad9-b274-91bd00be3a0b)

**Comment by rhamad4** [comment]
![image](https://github.com/user-attachments/assets/db01637b-1991-47a5-9e24-40c1ff14dedf)

**Comment by tareqissa** [comment]
@nadeemyaldani @rhamad4 @JarrarMo 
As discussed and agreed, it's better to rename the column name to "Created by" instead of "Role" to solve this issue

**Comment by rhamad4** [comment]
![image](https://github.com/user-attachments/assets/f0dd5900-e82d-4767-90e1-3941ac243abd)
fixed on QC
