### ISSUE TITLE
Page crashs when user click on the "Define Projects Weight" button  on the initiative page

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#132]
Steps: 
1.Login using rhamad/P@ssw0rd
2.Open the "http://rmpplus-qc.masterteam.sa/#/programs/55f1c6cc-5fec-418a-844b-9104e4c5fb37?program=55f1c6cc-5fec-418a-844b-9104e4c5fb37" link
3.Click on the "Define Projects Weight" button
4.click on the project weight drop down list and change the weight
5.Observe the screen

**Comment by nadeemyaldani** [comment]
It's working fine for me

Add a screenshot or a screen recording so i can see what's wrong @rhamad4

**Comment by nadeemyaldani** [comment]
![image](https://github.com/user-attachments/assets/d97a81eb-0d2a-4de8-9d59-4a09c2ea4907)

**Comment by nadeemyaldani** [comment]
![image](https://github.com/user-attachments/assets/2e495caf-f6da-4fad-9c64-e6304b6ec50c)

**Comment by rhamad4** [comment]
https://github.com/user-attachments/assets/4f0bd0fd-cfb4-415e-860a-0a9547d8cd7b

**Comment by nadeemyaldani** [comment]
Kindly check what's going here @SamerElaila 
![image](https://github.com/user-attachments/assets/5ac7248c-c415-4b13-816a-b4a6f590d249)

**Comment by rhamad4** [comment]
Checked on QC and working fine
it needs to be checked on stag

**Comment by rhamad4** [comment]
Checked on stag and passed
