### ISSUE TITLE
Tasks page does not downloaded

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#135]
![Image](https://github.com/user-attachments/assets/c396caf6-839f-4591-8901-58f951766fdc)

**Comment by tsartawiMW** [comment]
I beileve it is logged in user issue , it is SPAdmin user ,, I tried to login using my account and it opens 
![image](https://github.com/user-attachments/assets/84a55110-891f-4a40-8f85-b981e22b4b51)

**Comment by rhamad4** [comment]
fixed
