### ISSUE TITLE
The KPIs icon does not appear on the strategy page

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#136]
![Image](https://github.com/user-attachments/assets/32172c9d-4a4d-4fe5-b3ad-54340fea1fbe)

**Comment by tsartawiMW** [comment]
@nadeemyaldani 
could you please help me here , as I tried to update the KPI type , but I face this error 
![image](https://github.com/user-attachments/assets/37becc32-ed89-4700-9276-7d6fa00bf8a7)

**Comment by tsartawiMW** [comment]
I changes a record from DB and it seems working @rhamad4  please chcek and confirm

**Comment by rhamad4** [comment]
![Image](https://github.com/user-attachments/assets/ae07ea1a-08b7-4d6b-87bb-2a39bde9abc9)
fixed
