### ISSUE TITLE
Task Center: requests in Projects Tasks Approval is not being approved and keep as pending 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#14]
Steps: 

1. login as htaha/H@123456
2. go to tasks center and check Projects Tasks Approval
3. there is a task waiting action 
4. approve it then refresh the page 

Actual Result: 
the request will not be approved and still pending after refreshing the page (reject is working correctly) 

https://user-images.githubusercontent.com/110157969/193454677-1f65e27c-38ec-4280-8b35-5b84afb8042f.mp4

**Comment by JarrarMo** [comment]
@DemaHamideh cannot be reproduced.
I approved same task using heba user
![image](https://user-images.githubusercontent.com/53216161/193820289-d0f7a60f-4e42-40a1-a7b7-efb9d6bf0870.png)
