### ISSUE TITLE
Initiative Card: Initiative status is incorrectly reflected

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#15]
Steps:
1- login to the system (htaha, H@123456)
http://rmpplus-qc.masterteam.sa/#/programs-card

actual result: 
Initiative status is incorrectly reflected
![image](https://user-images.githubusercontent.com/107788214/193455441-d6ce3d97-755d-46c5-ab2e-7ca6c4380a34.png)

expected result: 
The initiative status should be "not started" only when all projects have "not started"
![image](https://user-images.githubusercontent.com/107788214/193455461-343b450c-7df1-4e9c-ab32-4c76c7cf917f.png)

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/193517341-6bfba8e9-a220-4776-b7d6-e3bd4a9dcbaf.png)

**Comment by hebaabutaha** [comment]
failed 
avg for actual progress = (65+0+0)\ 3 =21.66
avg for baseline progress = (20+0+0)\ 3 = 6.66

variance = 6.66 - 21.66 = - 14.99

-14.99 < 0 
so, the initiative status is not "delayed"

![image](https://user-images.githubusercontent.com/107788214/193766903-8108a236-abdc-454a-9115-8eb730d1a297.png)

![image](https://user-images.githubusercontent.com/107788214/193764937-16a2bdaf-4358-41b4-981c-46be69482f45.png)
![image](https://user-images.githubusercontent.com/107788214/193765017-5f9a0a26-d775-4fba-a457-0e4d3db2e539.png)
![image](https://user-images.githubusercontent.com/107788214/193765109-139149aa-8a47-4413-83ed-2547c24cf626.png)
![image](https://user-images.githubusercontent.com/107788214/193765218-462c6fd8-2a60-4971-8006-cf68cd417186.png)

**Comment by hebaabutaha** [comment]
recheck plz 
initiative/project status should be completed not on track 

![image](https://user-images.githubusercontent.com/107788214/194235634-81492153-e255-45e5-8cad-f73eefebf83c.png)
![image](https://user-images.githubusercontent.com/107788214/194236025-174427c5-8643-4b7a-b4d5-90d7a6ae8ef3.png)

**Comment by hebaabutaha** [comment]
QA retest passed 

![image](https://user-images.githubusercontent.com/107788214/194292598-0aacdf52-88e6-46a5-967a-5e0a9f8e75b0.png)
