### ISSUE TITLE
Project Workspace - Risks Tab: text needs to be modified 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#16]
![image](https://user-images.githubusercontent.com/110157969/193456276-9dba2e84-1393-47dd-b1ee-37db1d6d39fb.png)

![image](https://user-images.githubusercontent.com/110157969/193456329-c4e46a05-4162-4266-9f24-d7323f1df1e7.png)

![image](https://user-images.githubusercontent.com/110157969/193456488-1cdf21cb-96d3-457a-9e71-94e3f30020e0.png)

![image](https://user-images.githubusercontent.com/110157969/193475054-a6856d33-da4a-46c5-adf8-2e4addf99be5.png)

**Comment by JarrarMo** [comment]
No Business Requirements For The Form, We took vanilla design.

**Comment by JarrarMo** [comment]
@KhaldounAl-haj

**Comment by KhaldounAl-haj** [comment]
Confirmed

**Comment by KhaldounAl-haj** [comment]
Please change the labels as the following:
إضافة خطر جديد Add new risk
تفاصيل الخطر Description
حل الخطر Risk Soloution
تحويل الى مشكلة Transfer to an issue
@JarrarMo  this is also wrong on the vanilla version

**Comment by ealtiti** [comment]
<img width="1428" alt="Screen Shot 2022-10-04 at 4 40 33 PM" src="https://user-images.githubusercontent.com/85454412/193834946-8deffd1c-b275-40af-80b4-13c90b4ed8fa.png">
<img width="1428" alt="Screen Shot 2022-10-04 at 4 40 46 PM" src="https://user-images.githubusercontent.com/85454412/193834958-1945324a-d0d9-4de6-8d2e-2b481d723e9f.png">
<img width="1428" alt="Screen Shot 2022-10-04 at 4 40 49 PM" src="https://user-images.githubusercontent.com/85454412/193834964-6e8ae3fa-2c5d-4d42-8668-6c20e4324059.png">
<img width="1428" alt="Screen Shot 2022-10-04 at 4 41 17 PM" src="https://user-images.githubusercontent.com/85454412/193834968-fc52df18-385c-4cac-a0d9-299bb3e1b7ab.png">

**Comment by DemaHamideh** [comment]
below still exist 

![image](https://user-images.githubusercontent.com/110157969/194002102-77b34891-59a4-4308-b940-72ed032ba822.png)

**Comment by DemaHamideh** [comment]
Pass

![Uploading image.png…]()
