### ISSUE TITLE
Initiative Card: The actual progress is incorrectly rounded

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#17]
Steps:
1- login to the system (htaha, H@123456)
http://rmpplus-qc.masterteam.sa/#/programs-card

actual result:
(41+30)\4= 17.75
![image](https://user-images.githubusercontent.com/107788214/193455774-fd297f54-7d36-4c80-8a1b-63b38f7a2190.png)
![image](https://user-images.githubusercontent.com/107788214/193455851-22de48d3-c6ee-48f5-b6fb-39866266ebae.png)
![image](https://user-images.githubusercontent.com/107788214/193455871-4b13f20f-8f64-404f-9ad9-425111c9007d.png)

(10+15)\7= 3.57
![image](https://user-images.githubusercontent.com/107788214/193456125-4fd6e234-5504-41a2-8ce4-48e358bde551.png)
![image](https://user-images.githubusercontent.com/107788214/193455982-55b20732-ea1a-4b77-a816-6d902dbf36dc.png)
![image](https://user-images.githubusercontent.com/107788214/193456041-fa85899e-4e4c-4bc1-91f2-0814d64ac98b.png)

expected result: 
If the number after the comma is greater than5 (> 0.5), the % = Integer number +1
If the number after the comma is less than 5 (< 0.5), the % = Integer number

**Comment by JarrarMo** [comment]
Fixed, Kindly check.
![image](https://user-images.githubusercontent.com/53216161/193809761-6941ce31-bb4c-480f-b19e-646a71cac046.png)

**Comment by hebaabutaha** [comment]
plz Recheck

![image](https://user-images.githubusercontent.com/107788214/193998215-8ccef49a-f059-4cf3-af9d-2e025e3be49a.png)

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/194061035-2ebb8576-8ea8-4aba-bf5d-af5fcccead82.png)

**Comment by hebaabutaha** [comment]
QA retest passed 

![image](https://user-images.githubusercontent.com/107788214/194217789-1a978709-c395-4c71-8baa-adb4b1949064.png)
![image](https://user-images.githubusercontent.com/107788214/194217846-2a2391cf-1dbb-4e60-b2c4-202536764898.png)

![image](https://user-images.githubusercontent.com/107788214/194218416-24796be3-a286-48d0-8e37-4af1eca834e5.png)
![image](https://user-images.githubusercontent.com/107788214/194218467-6d05c03c-0a75-4705-9ce3-c11b3f06529a.png)
![image](https://user-images.githubusercontent.com/107788214/194218499-64791ed7-b9db-451a-8146-1cc51c057940.png)
![image](https://user-images.githubusercontent.com/107788214/194218543-38a7570c-7daf-4555-bc7b-7cbcae80b262.png)
