### ISSUE TITLE
Initiative permissions: all users in Executives group should see all projects

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#19]
Steps:
1- login to the system (halsaidi, Master@123)
http://rmpplus-qc.masterteam.sa/#/programs-card

actual result:
Some users in Executives group can't see any projects

![image](https://user-images.githubusercontent.com/107788214/193457328-ca071d88-436c-4c23-bbe9-55a94c4f6bf4.png)
![image](https://user-images.githubusercontent.com/107788214/193457393-c188a047-354a-4e64-98ba-f3d0da1af9a8.png)

expected result: 
all users in Executives group should see all projects

![image](https://user-images.githubusercontent.com/107788214/193457445-51f7afaf-354a-4cd5-8b7c-ddafd592822e.png)

**Comment by JarrarMo** [comment]
Fixed, Thank you.
![image](https://user-images.githubusercontent.com/53216161/193580574-80d7d289-109a-4345-bcbe-14d9c165cbaf.png)
![image](https://user-images.githubusercontent.com/53216161/193580609-5b8af4f7-e7d4-410f-a164-c984df70ab85.png)

**Comment by hebaabutaha** [comment]
QA retest passed 

![image](https://user-images.githubusercontent.com/107788214/193788583-715c6708-4739-44da-a531-dcb19432aae4.png)
![image](https://user-images.githubusercontent.com/107788214/193788723-e05dd852-2877-411d-81bc-25739eb36f05.png)
