### ISSUE TITLE
The username of the new user is displayed as unknown

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#2]
Steps:
1- login to the system (satieh/P@ssw0rd)
http://rmpplus-qc.masterteam.sa/#/programs-card
Actual result:
The username of the new user is displayed as unknown
![image](https://user-images.githubusercontent.com/107788214/193443678-ea4577e7-de68-4672-8549-1fb2173607ba.png)

expected result: 
The new username should display correctly

**Comment by JarrarMo** [comment]
This is related to users sync.
![image](https://user-images.githubusercontent.com/53216161/193443889-092fc86b-134a-4162-ae42-0b2ee8b2dd75.png)
