### ISSUE TITLE
Project Workspace - Milestones Tab: not start status is not exist 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#20]
Steps: 

1. login as dhamideh/D@12345
2. go to http://rmpplus-qc.masterteam.sa/#/project/f0bfd938-4271-4c88-b123-2987eff7714c/milestones

Actual Result: 
Milestone "not started, start at 5 Oct" status is on track while it should be not started, as the start date is 5 Oct

![image](https://user-images.githubusercontent.com/110157969/193459162-3169a9fb-9109-40a5-9fd3-b6ff34a4f88f.png)

http://94.127.212.109:2022/PWA/Project%20Detail%20Pages/Schedule.aspx?ProjUid=f0bfd938-4271-4c88-b123-2987eff7714c&ret=0

![image](https://user-images.githubusercontent.com/110157969/193459072-2f3cfea0-0c6f-4e14-b6e5-9c318ab9e0b3.png)

![image](https://user-images.githubusercontent.com/110157969/193459097-1bc6fe9e-9847-4d45-9290-950603e9dea8.png)

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/193806771-58109ed3-cf1f-4817-9704-a539a48d1a47.png)

**Comment by DemaHamideh** [comment]
Pass

![image](https://user-images.githubusercontent.com/110157969/193812918-aed55452-ebdb-478d-a817-f6973a59b48e.png)
