### ISSUE TITLE
Project Workspace - Documents Library Tab: phases names are shown in Ar in En version 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#21]
Steps: 

1. login as dhamideh/D@12345
2. go to http://rmpplus-qc.masterteam.sa/#/project/926790c9-a239-4a5c-a921-7bbc0c27c1be/documents
3. click on Project Documents 

Actual Result: 
phases names are shown in Ar in En version 

![image](https://user-images.githubusercontent.com/110157969/193459505-76799e7a-25dd-4e5d-a54d-1a9b7025b4d9.png)

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/193462440-b23bd985-324c-4ba2-9f28-743bdb6c9b5d.png)
![image](https://user-images.githubusercontent.com/53216161/193462445-e5dd7e7d-1b86-4017-9996-577630dee67f.png)

**Comment by DemaHamideh** [comment]
Closed as per Mohammad Jarrar and the confirmation in the comments

**Comment by DemaHamideh** [comment]
is it the same for this part also? to be shown in En in Ar mode? 

![image](https://user-images.githubusercontent.com/110157969/193476402-c679b58c-422e-4db6-ba44-697756e0b3d7.png)

**Comment by KhaldounAl-haj** [comment]
@DemaHamideh yes its the same
