### ISSUE TITLE
Project Workspace - Documents Library Tab: phases attachments are duplicated 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#23]
what is the need for showing phases attachments under "Project Documents" and showing them in the "System supporting Document"? 

![image](https://user-images.githubusercontent.com/110157969/193459825-7d336690-a9f2-4c36-acb1-0e569fc99edf.png)

**Comment by JarrarMo** [comment]
Thank you @DemaHamideh 
This is not duplicated,
The first set should read from Document Library from Project Site (folder names as required in CM)
The second set will read from phases as usual.

**Comment by DemaHamideh** [comment]
business issue, checked and pass
