### ISSUE TITLE
permissions: users in project owners & project sponsors groups can see all initiatives and projects

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#25]
Steps:
1- login to the system (test2, Master@123) or (test4, Master@123)
http://rmpplus-qc.masterteam.sa/#/programs-card

actual result:
users in project owners & project sponsors groups can see all initiatives and projects

![image](https://user-images.githubusercontent.com/107788214/193460056-9769c2fc-c353-4652-bddd-bac7f726a97e.png)
![image](https://user-images.githubusercontent.com/107788214/193460253-93a64968-208b-49cb-86d4-d1e52ee816da.png)

![image](https://user-images.githubusercontent.com/107788214/193460348-6398c62e-bcdc-471b-92c8-73ad34e04fca.png)
![image](https://user-images.githubusercontent.com/107788214/193460412-74d4cb9f-1ad8-459a-9afe-4a2f38e10d72.png)

expected result: 
users in project owners & project sponsors groups should only see related initiatives and projects
![image](https://user-images.githubusercontent.com/107788214/193460677-f1558b82-fb18-4735-9f33-e0db12362c91.png)

**Comment by hebaabutaha** [comment]
failed 
"Test 2" is the owner of "test 22222222222222" and "MJ TEST" projects 
"Test 4" is the sponsor of "Test 22222222222222" project

But "Test 2" & "Test 4" users can't see these projects
![image](https://user-images.githubusercontent.com/107788214/193796737-fc236109-7ec1-4a7d-aa39-0f86ac5e58d3.png)

![image](https://user-images.githubusercontent.com/107788214/193796827-14fdb923-7d9b-4ad0-9e96-c99bbb5487da.png)

![image](https://user-images.githubusercontent.com/107788214/193797006-590e9809-e5f2-4fba-a74c-0c6cdc1e7b36.png)
![image](https://user-images.githubusercontent.com/107788214/193797174-30e89cf8-f906-4828-a7a4-e682a8fd7e30.png)
![image](https://user-images.githubusercontent.com/107788214/193797311-daee23d4-5180-4c58-af3c-a46c58135817.png)

**Comment by JarrarMo** [comment]
@hebaabutaha Did you add it test2 and test4 to project team?

**Comment by JarrarMo** [comment]
@DemaHamideh @hebaabutaha 
Users Added automatically for Project "راعي المشروع"

![image](https://user-images.githubusercontent.com/53216161/193825201-3c3bc1aa-1068-4abc-9e73-1bf408214270.png)

![image](https://user-images.githubusercontent.com/53216161/193825228-da1bdeea-9d10-411c-8a37-8a0adf5e50e5.png)

**Comment by hebaabutaha** [comment]
QA retest passed 

![image](https://user-images.githubusercontent.com/107788214/194213110-8763e24f-6505-4658-b89b-7f99df7953e0.png)
![image](https://user-images.githubusercontent.com/107788214/194213186-8e5a8ec2-183f-433b-b01c-b9b4446dcd10.png)
![image](https://user-images.githubusercontent.com/107788214/194213489-8d5f6276-c0f3-4394-838a-4172ed6b28ca.png)
![image](https://user-images.githubusercontent.com/107788214/194213526-d23a3933-5d6e-4cf1-b8d8-a8dc3e39bfda.png)
![image](https://user-images.githubusercontent.com/107788214/194213577-5908456d-9c67-4920-b275-097d74e71fe7.png)
