### ISSUE TITLE
Permissions: users in Project Owners and Project Sponsors can view all system initiatives and projects 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#26]
1. Users in Project Owners and Project Sponsors can view all system initiatives and projects, is this the correct behavior, or they should be able to access the projects that they are related to them as owner or sponsor? 
as the BRD mentioned ذات الصلة, so please advise. 

![image](https://user-images.githubusercontent.com/110157969/193473272-1871e58b-9658-4dac-9b6a-b1d1979290d2.png)

2. we don't have portfolios, but we have portfolio groups "portfolio manager and portfolio viewer" that have the permission to view all initiatives and projects and appear in assigned to users, is this a correct behavior or should be excluded?

**Comment by DemaHamideh** [comment]
@KhaldounAl-haj 
what about the second point? 
2. we don't have portfolios, but we have portfolio groups "portfolio manager and portfolio viewer" that have the permission to view all initiatives and projects and appear in assigned to users, is this a correct behavior or should be excluded?

**Comment by DemaHamideh** [comment]
@JarrarMo 
as per Khaldon's feedback, currently, users in Project Owners and Project Sponsors groups can view all system initiatives and projects, but they should be able to access the projects that they are related to them as owners or sponsor.

**Comment by KhaldounAl-haj** [comment]
@JarrarMo please advise regarding the second point why do we have portfolio managers group

**Comment by JarrarMo** [comment]
For Sponsors
![image](https://user-images.githubusercontent.com/53216161/193539369-561b8102-71c5-47c3-9a33-cc81f4426c67.png)
![image](https://user-images.githubusercontent.com/53216161/193539874-52bcb43f-449c-42e3-83db-e41a501438e4.png)

**Comment by JarrarMo** [comment]
For Owners
Test2 has assigned risk , thats why he can see the initiative/project.
![image](https://user-images.githubusercontent.com/53216161/193540151-4036a8d2-9be6-4e6d-a59a-8f800157a915.png)
![image](https://user-images.githubusercontent.com/53216161/193540199-53ce5bdc-2c22-449a-8c49-e1f50be96197.png)

**Comment by DemaHamideh** [comment]
I've added a new project "D123456", where the owner is "Master_Admin" and the Sponsor is "test4" as shown below 

![image](https://user-images.githubusercontent.com/110157969/193772930-bbb63d52-bc69-4889-945c-786223fe256b.png)

but when logged as Master_Admin OR test4, nothing appears 

![image](https://user-images.githubusercontent.com/110157969/193773335-b4a9bcbc-ea19-41a8-8e07-7fdd0e1e4d2e.png)


![image](https://user-images.githubusercontent.com/110157969/193773577-d4c460fb-4c3d-4a46-a8f8-5a113d7dda7f.png)

**Comment by DemaHamideh** [comment]
@JarrarMo and please advise, we don't have portfolios, but we have portfolio groups "portfolio manager and portfolio viewer" that have the permission to view all initiatives and projects and appear in assigned to users, is this a correct behavior or should be excluded?

**Comment by JarrarMo** [comment]
@KhaldounAl-haj  @DemaHamideh Portfolio Manager and Viewer Groups are built-in groups, added by default to epm.

**Comment by JarrarMo** [comment]
@KhaldounAl-haj ,@DemaHamideh , As agreed with Hamza, we need to add the user to team using "Build Team" Tab.

**Comment by JarrarMo** [comment]
Users Added automatically for Project "راعي المشروع"
![image](https://user-images.githubusercontent.com/53216161/193824916-092f42f9-a532-4f72-9338-836695757e92.png)
![image](https://user-images.githubusercontent.com/53216161/193824992-18b5fb11-9b49-43a8-876a-3f56c0c98400.png)

**Comment by DemaHamideh** [comment]
Pass 

![image](https://user-images.githubusercontent.com/110157969/194000538-6871bdf1-b683-46fb-98e0-4a1306954cc2.png)
