### ISSUE TITLE
Project Workspace - Risks Tab: The category is not shown properly in view risks details 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#27]
Steps: 

1. login as test3
2. go to risks tab http://rmpplus-qc.masterteam.sa/#/project/f0bfd938-4271-4c88-b123-2987eff7714c/risks
3. add new risk and select category "Others" or check http://rmpplus-qc.masterteam.sa/#/project/f0bfd938-4271-4c88-b123-2987eff7714c/risks/details/5
4. OR don't select any category, keep the default value http://rmpplus-qc.masterteam.sa/#/project/f0bfd938-4271-4c88-b123-2987eff7714c/risks/details/6

Actual Result: 
The category is not shown properly
 
![image](https://user-images.githubusercontent.com/110157969/193474038-c53ec7e6-0c53-4fa9-9e61-23b2a3880305.png)

![image](https://user-images.githubusercontent.com/110157969/193474117-efc78783-f49d-409d-8e3e-043af70f1667.png)

**Comment by ealtiti** [comment]
fixed
<img width="1408" alt="Screen Shot 2022-10-04 at 10 59 26 AM" src="https://user-images.githubusercontent.com/85454412/193766223-17447d0f-1586-4f25-b209-42cbfcda27b0.png">
<img width="1408" alt="Screen Shot 2022-10-04 at 10 59 33 AM" src="https://user-images.githubusercontent.com/85454412/193766236-769f7421-6cd2-45b2-866d-c50d77a05153.png">

**Comment by DemaHamideh** [comment]
Pass 

![image](https://user-images.githubusercontent.com/110157969/194069638-f80eda2a-2ec2-4019-8135-c58d129a62cc.png)


![image](https://user-images.githubusercontent.com/110157969/194069713-a5f91b1c-6095-4130-bc75-ffbc14a7e757.png)


![image](https://user-images.githubusercontent.com/110157969/194069776-ed145d68-0deb-4a32-981a-e8f7b1963c62.png)
