### ISSUE TITLE
Project Workspace - Issues Tab: Action Plan is not mandatory in add new issue page as per the BRD 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#29]
![image](https://user-images.githubusercontent.com/110157969/193475770-e750af2e-99a1-4886-a4b7-b3a0cce89259.png)

**Comment by ealtiti** [comment]
fixed
<img width="1408" alt="Screen Shot 2022-10-04 at 11 01 13 AM" src="https://user-images.githubusercontent.com/85454412/193766532-edf0e87e-16b6-486e-8553-12f9ae2e1fe2.png">

**Comment by DemaHamideh** [comment]
Pass

![image](https://user-images.githubusercontent.com/110157969/193840849-093a74ac-fc47-4311-ba2d-8e18663fc939.png)
