### ISSUE TITLE
Create New Project: Strategic Pillar is not exist but it is mentioned in the BRD 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#3]
Steps:

1. login as PMO or Admin user (dhamideh/D@12345)
2. click on create new project 

Actual Result: 
Strategic Pillar is not exist but it is mentioned in the BRD 

![image](https://user-images.githubusercontent.com/110157969/193445778-cb99617e-d3ba-4304-93e5-9a6e57fcd79d.png)

**Comment by JarrarMo** [comment]
@hebaabutaha As Agreed with @HamzehJaddo , @KhaldounAl-haj 
Strategic Pillar is not ready till we integrate with S+

**Comment by KhaldounAl-haj** [comment]
@hebaabutaha @DemaHamideh Strategic pillar will be available when we integrate with RM S+

**Comment by tareqissa** [comment]
@HamzehJaddo your input please.

**Comment by KhaldounAl-haj** [comment]
@tareqissa @DemaHamideh @JarrarMo  this list will be fetched from S+

**Comment by DemaHamideh** [comment]
keep it in postponed list for now until it is ready
