### ISSUE TITLE
permissions: BRD mentioned that the system should have the initiative sponsors group 

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#30]
Steps:
1- login to system (epmadmin, Master@123)
http://rmpplus-qc.masterteam.sa/#/programs-card
http://94.127.212.109:2022/PWA/_layouts/15/pwa/Admin/ManageGroups.aspx

actual result: 
The EPM system does not have the initiative sponsor group

![image](https://user-images.githubusercontent.com/107788214/193509639-7afa6909-0ecd-4531-8143-588c284e715d.png)
![image](https://user-images.githubusercontent.com/107788214/193509745-22967502-efee-449d-b4de-04b30599b7fd.png)

**Comment by KhaldounAl-haj** [comment]
@JarrarMo please advise

**Comment by JarrarMo** [comment]
@hebaabutaha added, kindly check the permission.
Kindly remove business label, its a bug.

@saqratieh

**Comment by hebaabutaha** [comment]
failed 
Initiatives sponsors group should see their initiatives and all projects on those initiatives
![image](https://user-images.githubusercontent.com/107788214/193801448-26eaef81-8f83-480e-b5b7-ef225ec04646.png)
![image](https://user-images.githubusercontent.com/107788214/193801924-d3659164-c051-42ae-ad6d-8e53d34c4b95.png)
![image](https://user-images.githubusercontent.com/107788214/193802116-7e746d7f-daea-411c-8d92-917a934609b9.png)

**Comment by JarrarMo** [comment]
@hebaabutaha please check permission settings with @DemaHamideh 
its the same as implemented in OSP

@saqratieh , @HamzehJaddo fyi

**Comment by hebaabutaha** [comment]
As per discussion with Hamzah, the initiative sponsor group should be removed from EPM @JarrarMo 
plz advise @KhaldounAl-haj

**Comment by KhaldounAl-haj** [comment]
@JarrarMo Confirmed please remove the initiative sponsor group

**Comment by JarrarMo** [comment]
@hebaabutaha group removed, kindly remove bug label
@saqratieh @KhaldounAl-haj 
![image](https://user-images.githubusercontent.com/53216161/194061364-e3afc29d-385b-42b0-ae9d-bbeb59b83ecf.png)

**Comment by hebaabutaha** [comment]
updated 
![image](https://user-images.githubusercontent.com/107788214/194748490-ff1501bd-8c43-40b1-8039-ba2d142623e6.png)
