### ISSUE TITLE
Task Center - Phase Approvals: more data should be shown here 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#31]
Actual Result: 

![image](https://user-images.githubusercontent.com/110157969/193516478-c819346b-883b-4ffb-aa4a-99dd58688adf.png)

Expected Result: 
more data should be shown like: Project Name, Current Phase, next Phase ... or other data as per the business needs 

@KhaldounAl-haj please advise about the correct data to be shown, as the BRD screenshot is wrong and not show the phase approvals screen, and update it please.

**Comment by JarrarMo** [comment]
@DemaHamideh Valid point, kindly make it as enhancement and not a bug, since no specific requirements were provided.

**Comment by KhaldounAl-haj** [comment]
@JarrarMo i will provide you with the xtra 2 coloumns for the master version

**Comment by ealtiti** [comment]
FE Done  @JarrarMo 
<img width="1428" alt="Screen Shot 2022-10-05 at 1 53 03 PM" src="https://user-images.githubusercontent.com/85454412/194044387-ec2bbc50-9d9c-4ff7-89bc-d595668f2d0d.png">
<img width="1428" alt="Screen Shot 2022-10-05 at 1 53 08 PM" src="https://user-images.githubusercontent.com/85454412/194044405-b87a874a-31c3-471a-aae5-80941819ba82.png">

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/194062949-b80853cc-0d3b-44a1-bac3-42a9b711c72f.png)
![image](https://user-images.githubusercontent.com/53216161/194062987-1463c441-e40e-4f3e-8ddd-8cdb6bcf9373.png)
