### ISSUE TITLE
permissions: project managers Group cannot prepare a schedule for related projects

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#33]
Steps:
1- login to system (test3, Master@123)
http://rmpplus-qc.masterteam.sa/#/programs-card
http://94.127.212.109:2022/PWA/_layouts/15/pwa/Admin/ManageGroups.aspx

actual result: 
project managers Group cannot prepare a schedule for related projects
![image](https://user-images.githubusercontent.com/107788214/193519334-3e1ed5c7-daf9-4d51-a846-1c7a36972fe6.png)

expected result: 

![image](https://user-images.githubusercontent.com/107788214/193519593-32ab6fe5-d416-4e59-b672-bf21bb9ae3f9.png)

**Comment by JarrarMo** [comment]
test3 is not admin, he cannot edit groups
as verified with @hebaabutaha , its not a bug.

**Comment by JarrarMo** [comment]
kindly remove bug label.

**Comment by JarrarMo** [comment]
@hebaabutaha I tried using test3, htaha on MS Project , and the above message show, project managers group cannot set baseline.

**Comment by JarrarMo** [comment]
@hebaabutaha baseline permission will be from managers groups regardless if user in admin or not, kindly take in consideration that ib real life scenario project manager will not be an admin in same time

@KhaldounAl-haj , @HamzehJaddo kindly advise

**Comment by KhaldounAl-haj** [comment]
@JarrarMo @hebaabutaha as mentioned by jarrar the project manager cannot be an admin and a project manager at the same time we do that for testing purposes only.

and regarding baseline we only use baseline 0.

@JarrarMo thank you for the clarification

**Comment by hebaabutaha** [comment]
thank u 

Qa retest passed 

![image](https://user-images.githubusercontent.com/107788214/194229054-1d6e2df2-7fe3-42df-a88e-96a643dad851.png)
