### ISSUE TITLE
Task Center - Projects Tasks Approval: Project mane in English text should be modified in Arabic version, and the BRD need to be updated to be as per to what is implemented 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#34]
Actual Result: 

![image](https://user-images.githubusercontent.com/110157969/193521833-05bd7ac8-753f-4ec2-b703-b11323cdf73c.png)

Expected Result: 
1. the title اسم المشروع بالانجليزية should be اسم المشروع 

2. @KhaldounAl-haj the screenshot in BRD should be updated as below to be matched with what is implemented which is more correct

![image](https://user-images.githubusercontent.com/110157969/193523057-d236df11-b9a5-4a41-a5ee-8940a320c599.png)

**Comment by KhaldounAl-haj** [comment]
thank you for the note i will provide version 1.2 for the CM after we finish testing in case of any other changes

**Comment by DemaHamideh** [comment]
@JarrarMo check the first screenshot please, the shown name is the project name in Arabic, thus the label should be اسم المشروع only

**Comment by ealtiti** [comment]
Project name fixed 
<img width="1428" alt="Screen Shot 2022-10-04 at 5 06 53 PM" src="https://user-images.githubusercontent.com/85454412/193841232-f3a7d39d-54d8-4ff1-8e57-503fdcf870ac.png">

**Comment by DemaHamideh** [comment]
Pass 

![image](https://user-images.githubusercontent.com/110157969/194006397-10aa9ef0-39ef-4b74-8e47-eef09ecf9c42.png)

**Comment by DemaHamideh** [comment]
will be closed after checking the updated configuration manual

**Comment by DemaHamideh** [comment]
C.M. updated V1.2 

![image](https://user-images.githubusercontent.com/110157969/194748694-44da8741-f40d-4d77-b6fa-073739259051.png)
