### ISSUE TITLE
Notification: Notification received on system only (no email notifications)

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#35]
Steps:
1- login to the system (htaha, H@123456)
2- go to project workspace 
3- create new risk/issue

http://rmpplus-qc.masterteam.sa/#/project/bf976c39-df2f-4846-941e-7fab2764ac6b/risks

actual result: 
Notification received on system only (no email notifications)

**Comment by hebaabutaha** [comment]
Plz advice, @KhaldounAl-haj 
Should users receive email notifications or not?

**Comment by KhaldounAl-haj** [comment]
@hebaabutaha no email notfications

**Comment by JarrarMo** [comment]
@hebaabutaha Kindly remove bug label, email was not required.
@saqratieh fyi

**Comment by saqratieh** [comment]
@KhaldounAl-haj  should we support Email notification?
