### ISSUE TITLE
project card: The project name should be aligned

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#36]
Steps:
1- login to system (htaha, H@123456)
2- go to project workspace 
http://rmpplus-qc.masterteam.sa/#/project/bf976c39-df2f-4846-941e-7fab2764ac6b/risks/details/2

actual result:
![image](https://user-images.githubusercontent.com/107788214/193527026-ddd8bf7c-da3e-4832-bb30-f0134f3c9b13.png)

expected result: 
The project name should be aligned

**Comment by JarrarMo** [comment]
@hebaabutaha This is default implementation, please remove the bug label and make it as enhancement.

@saqratieh fyi

**Comment by JarrarMo** [comment]
This is invalid scenario, project name container already will wrap the text according to spaces, and this is single word without any.
@hebaabutaha 
@saqratieh

**Comment by saqratieh** [comment]
@hebaabutaha can you please add a logical project name? Please test Ar and En names

**Comment by hebaabutaha** [comment]
correct 
![image](https://user-images.githubusercontent.com/107788214/193757375-4a4a4cb3-9d84-4e64-9b64-0691fefee3cd.png)
![image](https://user-images.githubusercontent.com/107788214/193757451-83c330cf-c2a0-4196-9a19-906ca00b166a.png)
