### ISSUE TITLE
Task Center - Approvals: confirmation message should be added for any approve/reject action &&& for Risks/Issues Close and transfer to issue actions

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#37]
1. for any approve or reject actions, a confirmation message should appear "Are you Sure?" with a comment text area that should be mandatory in the rejection process. 
2. this also should be applied in Phase Gate page. 
3. add it also to Risks/Issues for Close and transfer to issue actions, the are you sure popup without the comment box

**Comment by JarrarMo** [comment]
@tareqissa , @NAlzahrani you want general message for all modules?

please provide arabic and english translation.

**Comment by tareqissa** [comment]
@KhaldounAl-haj 
please we need your support in this and let us discuss before we confirm to the team.

**Comment by KhaldounAl-haj** [comment]
@tareqissa @JarrarMo Please consider the following:

English: "Are you sure?" Buttons (Yes,No)
Arabic: هل انت متأكد؟" الأزرار (نعم,لا)"

**Comment by tareqissa** [comment]
@KhaldounAl-haj I thought it will specific confirmation for each action, I think this is fair
@JarrarMo any concern on this?

**Comment by KhaldounAl-haj** [comment]
@tareqissa  i thought there's no need to complicate things, that would do what's needed and it's clear.

**Comment by JarrarMo** [comment]
@tareqissa , @KhaldounAl-haj yes a generic message to all items would be better and easier for implementation.

**Comment by JarrarMo** [comment]
@tareqissa if you need to implement a specific message for each module kindly state that before we start.

**Comment by tareqissa** [comment]
Confirmed @JarrarMo for the generic message..

**Comment by DemaHamideh** [comment]
Fixed
