### ISSUE TITLE
Task Center - Approvals: the count is not correct 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#38]
![image](https://user-images.githubusercontent.com/110157969/193531261-7418c4f0-3e9e-4ca2-bc32-996b4d38b6d8.png)

![image](https://user-images.githubusercontent.com/110157969/193531590-a18d0677-e9e1-4f3e-92e5-77357673d9b5.png)

![image](https://user-images.githubusercontent.com/110157969/193531679-a4b3de90-69a3-4613-abdc-d27f5d6497c5.png)

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/194013234-e4bfb349-463c-40a8-aa86-414a9447dc2d.png)
![image](https://user-images.githubusercontent.com/53216161/194013286-d4256847-cda1-4032-be72-5320e9206c1d.png)

**Comment by JarrarMo** [comment]
@DemaHamideh fixed for My Requests, My Tasks Tabs

For Approvals, it's not implemented before, we will work on it later, it needs extra work.

**Comment by KhaldounAl-haj** [comment]
@JarrarMo we can consider this as an enhancement for the master version

**Comment by DemaHamideh** [comment]
Pass

![image](https://user-images.githubusercontent.com/110157969/194077741-3af52342-58ed-459e-a30f-1aaeb7fe2ac4.png)

![image](https://user-images.githubusercontent.com/110157969/194077779-38104219-2297-4a91-93d2-472cfc9c4b25.png)

**Comment by DemaHamideh** [comment]
Postponed for Approvals tab

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/197556861-3bfc13c3-0c59-461b-bb30-96bf8e1066a2.png)

**Comment by DemaHamideh** [comment]
Fixed 

Epmadmin 

![image](https://user-images.githubusercontent.com/110157969/197959820-db529981-2a25-4b2a-b825-0c24afe1b311.png)


Hiba 

![image](https://user-images.githubusercontent.com/110157969/197959974-3b0e6106-df30-46ef-9db1-ea6a6eda84a4.png)
