### ISSUE TITLE
Task Center - My Tasks: show the manager who is responsible to approve/reject the task updates same as projects tasks

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#39]
1. show the status manager (or whatever is his name, but the user who is responsible to approve/reject the task updates should be shown same as projects tasks)
2. I believe that there is no need to show assigned to as it is will be always assign to me as a user 

![image](https://user-images.githubusercontent.com/110157969/193533413-28823203-c049-4bfe-b117-a8343a5d046d.png)

**Comment by JarrarMo** [comment]
@KhaldounAl-haj kindly advise.

**Comment by KhaldounAl-haj** [comment]
@DemaHamideh this field is added for the managers to check who's assigned on this task it is needed for future work and its a vanilla version default implementation we cant edit it unless the client wants to change

**Comment by DemaHamideh** [comment]
@KhaldounAl-haj 
what about the first point: 
show the status manager (or whatever is his name, but the user who is responsible to approve/reject the task updates should be shown same as projects tasks)

**Comment by KhaldounAl-haj** [comment]
@DemaHamideh we will consider this on the master version thank you.

**Comment by JarrarMo** [comment]
@KhaldounAl-haj , @DemaHamideh kindly explain what exactly is needed here.

**Comment by DemaHamideh** [comment]
show the status manager ( the user who is responsible to approve/reject the task updates) 
like below 

![image](https://user-images.githubusercontent.com/110157969/198001456-f88ebda4-ac9c-47cf-8779-cc71375a97f5.png)

**Comment by tareqissa** [comment]
hello @DemaHamideh as discussed and agreed, in Vanilla version this field is not available and it's nice to have it but not in this phase, let's postpone it to second phase please.
