### ISSUE TITLE
Create New Project: تاريخ البداية to be تاريخ البدء as per the BRD

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#4]
Steps:

1. login as PMO or Admin user (dhamideh/D@12345)
2. click on create new project 

Actual Result: 
the text تاريخ البداية should be تاريخ البدء 

![image](https://user-images.githubusercontent.com/110157969/193445984-4726f8ba-0a8f-4ebd-8e92-bc53454f8b90.png)

**Comment by JarrarMo** [comment]
@KhaldounAl-haj Kindly share the latest version of CM, I believe we agreed on all labels.

**Comment by KhaldounAl-haj** [comment]
@JarrarMo @DemaHamideh please check RM space for the latest CM
