### ISSUE TITLE
notifications (phase gate): project manager & project owner do not receive a notification when the request to move the project from phase to another is (rejected/ or approved)

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#40]
Steps:
1- login to system (htaha, H@123456)
http://rmpplus-qc.masterteam.sa/#/project/bf976c39-df2f-4846-941e-7fab2764ac6b/phase-gate

actual result: 
The project manager & project owner do not receive a notification when the request to move the project from phase to another is rejected
![image](https://user-images.githubusercontent.com/107788214/193533941-70c6b9e7-8cbd-4ac7-933b-29926677d29d.png)

expected result: 
![image](https://user-images.githubusercontent.com/107788214/193535574-4241c310-f32c-4104-b895-6187e26c5f19.png)

**Comment by JarrarMo** [comment]
@hebaabutaha its working, I could not re-produce the scenario, would you kindly double check.
![image](https://user-images.githubusercontent.com/53216161/193573175-da856ab7-a30a-4da5-bec2-1ce709cd7a14.png)

![image](https://user-images.githubusercontent.com/53216161/193573010-5fc4d354-b6fa-4a12-a1a4-bc21677b2431.png)
![image](https://user-images.githubusercontent.com/53216161/193573117-09cc1529-3852-4846-9794-d7f16a15a16b.png)

**Comment by hebaabutaha** [comment]
working fine
I think it was a data issue related to project

![image](https://user-images.githubusercontent.com/107788214/193768997-d900811d-8e21-40e5-a2c5-08c667905bec.png)
![image](https://user-images.githubusercontent.com/107788214/193769140-a0965a02-ab0e-4505-82e9-ff17ee550ef4.png)
