### ISSUE TITLE
notifications (phase gate): The project is in the closure phase and the system sends a notification that the project has moved to the closure phase

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#41]
Steps:
1- login to system (htaha, H@123456)
http://rmpplus-qc.masterteam.sa/#/project/bf976c39-df2f-4846-941e-7fab2764ac6b/phase-gate

actual result: 
The project is in the closure phase and the system sends a notification that the project has moved to the closure phase
![image](https://user-images.githubusercontent.com/107788214/193538793-846b76a4-0441-4cd4-bd42-df098793b9d2.png)
![image](https://user-images.githubusercontent.com/107788214/193538967-fa4f0a12-ed37-431e-99eb-7b742eaa49e3.png)

expected result: 
When the project moves from the closure phase (the closure phase has been completed), the notification text should be different from what the user actually receives

**Comment by KhaldounAl-haj** [comment]
![image](https://user-images.githubusercontent.com/100074546/193905725-227c100b-c90f-4d96-8486-88eac566f7f4.png)
@JarrarMo Please use this template

**Comment by JarrarMo** [comment]
I updated "تمت" to "تم" in case of rejection.

**Comment by hebaabutaha** [comment]
Main issue passed, but please update the notification text sent to PMO

![image](https://user-images.githubusercontent.com/107788214/194216033-215868fd-1a3e-4082-9f71-e64e48e39bb6.png)
![image](https://user-images.githubusercontent.com/107788214/194216166-10b988e3-524e-4c9b-8d19-a6779e5849fa.png)

passed 

![image](https://user-images.githubusercontent.com/107788214/194216414-cc60cc58-a92f-4014-96c6-fd935511a911.png)
![image](https://user-images.githubusercontent.com/107788214/194216518-ed1fcd2b-1d8d-4fdf-a26b-4c755ddd42dd.png)

**Comment by JarrarMo** [comment]
@hebaabutaha no template provided for the submit, I applied templates added by @KhaldounAl-haj and he confirmed it.

Kindly close it and remove re-opened label

@saqratieh kindly advise

**Comment by hebaabutaha** [comment]
PMO receives incorrect notification text @KhaldounAl-haj 
So, Can you provide us with another template for the notifications that the PMO receives when user submits a request to complete the closure phase, Plz

**Comment by KhaldounAl-haj** [comment]
@JarrarMo  @hebaabutaha PMO shall recieve the same message as the Project Manager and Project owner
تمت الموافقة على/رفض طلب إنهاء مرحلة الإغلاق للمشروع " اسم المشروع" من قبل " المستخدم"

Project closure Phase for “Project Name” has been Approved/Rejected by “User”

**Comment by hebaabutaha** [comment]
A new request has been submitted for the project “to end the closure phase by”, please review the checklist and attachments and take the appropriate decision
تم تقديم طلب جديد للمشروع "  " لانهاء مرحلة الاغلاق بواسطة " "، يرجى مراجعة قائمة التحقق والمرفقات واخذ القرار المناسب

**Comment by KhaldounAl-haj** [comment]
تم تقديم طلب إنهاء مرحلة الإغلاق للمشروع " اسم المشروع" بواسطة "المستخدم" ، يرجى مراجعة قائمة التحقق والمرفقات وأخذ القرار المناسب
A Project closure request has been submitted for the project “Project Name” by “User”, Please review the checklist and the attachments and take the appropriate decision

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/197526339-0c7b80d7-8e29-48a7-a511-6665ef81fcd9.png)
![image](https://user-images.githubusercontent.com/53216161/197526384-726ab6a7-7a8c-4d8a-912d-7bea5071ca21.png)

**Comment by hebaabutaha** [comment]
passed 
![image](https://user-images.githubusercontent.com/107788214/197948339-2d62b1b5-e2b7-4bf8-926e-e66885aebe64.png)
![image](https://user-images.githubusercontent.com/107788214/197948431-ed4eef70-6490-419d-9f19-b68b6648394c.png)
