### ISSUE TITLE
Task Center - My Requests && My Tasks: the Last Change Status should be "New" not "Pending" for new added tasks 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#43]
Steps: 

1. from test4 add new task assigned to epm from my requests tab 
2. open epm anfd go to my tasks to check the added task 
3. to check my requests login as test4  http://rmpplus-qc.masterteam.sa/#/tasks/requests ((from test4 to epm))
4. to check my tasks login as epmadmin  http://rmpplus-qc.masterteam.sa/#/tasks/my-tasks ((from test4 to epm))
5. check the Last Change Status that appears as pending

Actual Result: 
this is new added task and no action is done on it yet, thus the Last Change Status should be "New" not Pending

**Comment by KhaldounAl-haj** [comment]
@DemaHamideh we don't have "new" status for the tasks nor it was mentioned in the manual.

we might consider this for the master version if the client approves it but this is invalid expectation.

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/197795909-73f60642-6e14-442c-b442-11043c51f003.png)

**Comment by DemaHamideh** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/110157969/197960994-4189e474-715f-446d-8d37-eb1d700a79fe.png)
