### ISSUE TITLE
Task Center - My Tasks && Tasks Approvals: attachments disappear after updating a task and wont shown in Tasks Approvals

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#44]
submit task update from my tasks tab with attachments: 
login using epm then open http://rmpplus-qc.masterteam.sa/#/tasks/my-tasks 

![image](https://user-images.githubusercontent.com/110157969/193563419-5afd43e2-64c4-4d57-9cdd-62348c5ad2a4.png)

![image](https://user-images.githubusercontent.com/110157969/193562921-5f08d6c4-1fa4-41e9-abdf-8209dd158a8f.png)

after submitting, open it after a short while "No attachments shown": 

![image](https://user-images.githubusercontent.com/110157969/193563479-89929030-c57a-43a9-9742-3484b72a8636.png)

open it in approval tasks "No attachments shown": 
login using test4 then open  http://rmpplus-qc.masterteam.sa/#/tasks/approvals

![image](https://user-images.githubusercontent.com/110157969/193563691-be361c09-f753-422a-8508-adf9cd9132bc.png)

![image](https://user-images.githubusercontent.com/110157969/193563721-4376144f-2f4e-47b2-94f3-ee38590c846e.png)

**Comment by JarrarMo** [comment]
@ealtiti please inform me if this needs BE.

**Comment by JarrarMo** [comment]
@ealtiti please call Task By ID to return attachments.

**Comment by JarrarMo** [comment]
As we agreed, we will use the below
NP Task
TaskCenter/NonProjectTasks/Attachments/{id}
Project Task 
TaskCenter/Assignment/Attachments/{id}

**Comment by ealtiti** [comment]
fixed 
<img width="1341" alt="Screen Shot 2022-10-29 at 12 22 32 PM" src="https://user-images.githubusercontent.com/85454412/198824357-37b0e375-5115-49fe-8b4a-3038daa2af10.png">
<img width="1341" alt="Screen Shot 2022-10-29 at 12 24 15 PM" src="https://user-images.githubusercontent.com/85454412/198824364-a2c6afc7-a8f5-4dba-ab03-dd2a9cb4d247.png">
<img width="1341" alt="Screen Shot 2022-10-29 at 12 31 33 PM" src="https://user-images.githubusercontent.com/85454412/198824365-f73477e8-4dae-4668-bd8c-272e215e8b60.png">

**Comment by DemaHamideh** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/110157969/198867253-6a4ab124-601a-4018-aa80-84397bc8144b.png)


![image](https://user-images.githubusercontent.com/110157969/198867266-2b0bd3bc-5d27-42eb-b879-1fa8664e37bf.png)
