### ISSUE TITLE
Notifications: Adjust the following text

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#47]
- close risk/issue (no space before ("))
should be 
"for close risk"  
![image](https://user-images.githubusercontent.com/107788214/193525342-fad2507c-d9f6-4fa2-b70d-c5f7f8626caf.png)
![image](https://user-images.githubusercontent.com/107788214/193526480-4ef0ad63-3e3f-486a-9129-9c7ea9fe63c5.png)

- non-project task (no space before ("))
![image](https://user-images.githubusercontent.com/107788214/193551831-399d7617-3f4c-4d73-916f-17f84009dc96.png)
![image](https://user-images.githubusercontent.com/107788214/193552039-73fe07a6-6e61-4a57-bc0d-9a82bdb00ead.png)
![image](https://user-images.githubusercontent.com/107788214/193552614-335bdf9c-7088-4762-a4cf-68ce1b987dc8.png)
![image](https://user-images.githubusercontent.com/107788214/193552786-86b4986f-00ef-4900-bd2c-9020db19572f.png)
![image](https://user-images.githubusercontent.com/107788214/193553603-54dadca0-d84e-4186-a929-f21257bc285a.png)
![image](https://user-images.githubusercontent.com/107788214/193554128-f59dee3b-57d8-4b47-8c67-786165e1ecf5.png)
![image](https://user-images.githubusercontent.com/107788214/193554219-883bd240-1907-4c66-a73f-5516949f2055.png)

- use Arabic comma
![image](https://user-images.githubusercontent.com/107788214/193531426-567eef42-5914-44cc-9155-4dc2a2aa6144.png)
![image](https://user-images.githubusercontent.com/107788214/193749455-f003c5b8-0313-403b-a60d-e5c6818fa59f.png)

**Comment by JarrarMo** [comment]
@hebaabutaha I believe this is invalid bug, the space at the end exists already in risk title and task name
and for the phase gate, the response is correct with arabic comma, but it seems the system font doesnt support it.
![image](https://user-images.githubusercontent.com/53216161/193876928-b2460edf-b007-4b11-9a75-557a0cc2f3db.png)
