### ISSUE TITLE
Project Workspace - Deliverables and Milestones Tabs: Long Deliverables/Milestones Names are not shown correctly in P+ 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#49]
![image](https://user-images.githubusercontent.com/110157969/193574485-da132b56-c6f8-41a0-a241-7101c9f1ef14.png)

![image](https://user-images.githubusercontent.com/110157969/193574884-4ac51da8-f6e2-4566-bdbb-b721b3f02fc8.png)

**Comment by JarrarMo** [comment]
@KhaldounAl-haj this is also related to default implementation.

**Comment by JarrarMo** [comment]
@KhaldounAl-haj kindly confirm or advise.

**Comment by KhaldounAl-haj** [comment]
Confirmed @JarrarMo

**Comment by KhaldounAl-haj** [comment]
@JarrarMo just trim the extra text and add "..." and on mouse hover the user can read the rest of the name

**Comment by DemaHamideh** [comment]
Pass

![image](https://user-images.githubusercontent.com/110157969/194051106-b2fb0c06-dff1-423b-bae8-151ada42a912.png)

![image](https://user-images.githubusercontent.com/110157969/194051175-f0500fd7-f6f2-475a-abc8-7a5d5b6a6b12.png)
