### ISSUE TITLE
Create New Project: show warning message when fill an exist project name 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#5]
Steps:

1. login as PMO or Admin user (dhamideh/D@12345)
2. click on create new project 
3. fill all the fields and add exist project name
4. click on submit 

Actual Result: 

![image](https://user-images.githubusercontent.com/110157969/193447805-c389f89d-0b72-4898-8aa5-18271b0781fa.png)

Expected Result: 
an indicator or warning message should appear to be clear to the user that it is duplicated name rather than the border red on the field which will not be clear to the user in this way

**Comment by JarrarMo** [comment]
As agreed with @KhaldounAl-haj , the message will show as tooltip.

**Comment by KhaldounAl-haj** [comment]
@hebaabutaha confirmed

**Comment by DemaHamideh** [comment]
Still nothing appears 

https://user-images.githubusercontent.com/110157969/193758818-6317c754-cec6-48d2-b084-20f51c0d67a3.mp4
