### ISSUE TITLE
Permissions: Users in a PMO group should see all initiatives/projects, they can create a new project, & approve/reject phase gate requests

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#51]
Steps:
1- login to the system (test1, Master@123) 
http://rmpplus-qc.masterteam.sa/#/programs-card

actual result: 
![image](https://user-images.githubusercontent.com/107788214/193579782-b3d0106f-5129-414c-9b3c-203ed6b019c1.png)
![image](https://user-images.githubusercontent.com/107788214/193583265-e0feb940-7ffa-464d-a44d-17d04a55bb81.png)

After adding the user to the member group, the initiatives appear as in the following picture
![image](https://user-images.githubusercontent.com/107788214/193581767-b7b86acb-1145-40a3-b1ba-7764c901b7d4.png)

expected result: 
Permissions: Users in a PMO group should see all initiatives/projects, they can create a new project, & approve/reject phase gate requests

![image](https://user-images.githubusercontent.com/107788214/193579914-20f45078-d901-4a6c-ae6e-25ab59cc56ac.png)

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/193777789-8acd4186-d9b4-4222-855c-1976ff7121fe.png)

**Comment by hebaabutaha** [comment]
QA retest passed 
![image](https://user-images.githubusercontent.com/107788214/193785474-ffbdc92b-dd92-43a7-9f73-a018159e8875.png)
![image](https://user-images.githubusercontent.com/107788214/193785824-c1021bf5-6684-4398-a879-b98de420a476.png)
