### ISSUE TITLE
login page: The login page must match the design (A Tooltip should be added to the username and password fields)

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#52]
actual result: 
![image](https://user-images.githubusercontent.com/107788214/193759131-dda2cefe-b079-4119-9523-f618c8aabc90.png)

expected result: 
The login page must match the design (A Tooltip should be added to the username and password fields)
![image](https://user-images.githubusercontent.com/107788214/193759216-1c01ce28-492e-4432-afbd-5ebb0c0c8f33.png)

**Comment by ealtiti** [comment]
fixed 
<img width="1408" alt="Screen Shot 2022-10-04 at 10 49 07 AM" src="https://user-images.githubusercontent.com/85454412/193764148-e6e0f78f-079e-44e1-bd28-96a59753d174.png">

**Comment by hebaabutaha** [comment]
QA retest passed 

![image](https://user-images.githubusercontent.com/107788214/193996950-6c6b4668-ca2a-45ff-a67a-e8696adee497.png)
