### ISSUE TITLE
project status: project status (on hold / cancelled / or archived) not reflect on p+

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#53]
Steps:
1- login to the system (htaha, H@123456)
http://rmpplus-qc.masterteam.sa/#/project/8cbbf983-4d13-449c-bfd8-33e1e1e3ad28/preview
http://rmpplus-qc.masterteam.sa/#/project/c6523c06-e1e0-43ae-9aa3-2b0f063a9629/preview
http://rmpplus-qc.masterteam.sa/#/project/5f6150a5-7281-4b99-bd39-2c3508d8ff2e/preview

actual result: 
project status (on hold / cancelled or archived) not reflect on p+
![image](https://user-images.githubusercontent.com/107788214/193776544-6a42c665-e609-462a-af46-5d10d7fdbfc0.png)
![image](https://user-images.githubusercontent.com/107788214/193779751-c8510a48-ac88-4012-ada7-18675ce7be3a.png)

![image](https://user-images.githubusercontent.com/107788214/193779859-a5d6d078-2426-4438-82fa-47c9f747bccf.png)
![image](https://user-images.githubusercontent.com/107788214/193779976-6cd7ccf4-32dd-4fe5-b371-f042069834bf.png)

![image](https://user-images.githubusercontent.com/107788214/193786393-8487cd67-bf53-440c-9026-6346db8e8706.png)
![image](https://user-images.githubusercontent.com/107788214/193786528-2bbb88df-89e2-422f-a0e4-2ca04a116bac.png)

expected result: 
![image](https://user-images.githubusercontent.com/107788214/193778368-deb66de6-ffc9-41d1-a499-eca3c92c78fb.png)

**Comment by JarrarMo** [comment]
Projects Count Without Cancelled
![image](https://user-images.githubusercontent.com/53216161/193795072-af22472c-774f-4175-b87d-64d5925f142b.png)

**Comment by JarrarMo** [comment]
On Hold
![image](https://user-images.githubusercontent.com/53216161/193795186-ee6181e5-52d9-442f-9bc4-e913882587f3.png)
Cancelled
![image](https://user-images.githubusercontent.com/53216161/193795483-d3ddb27a-a7d0-41d4-95eb-2aa5a5fa4d7a.png)
Archived will not show in Program's Projects, we will not have archived projects

![image](https://user-images.githubusercontent.com/53216161/193795614-9ddec0fa-6367-496a-aa7d-474ddb8e5e88.png)

**Comment by JarrarMo** [comment]
@hebaabutaha kindly ignore the last screenshot, it will not appear in pplus.

**Comment by hebaabutaha** [comment]
QA retest passed 

![image](https://user-images.githubusercontent.com/107788214/194047821-cf74c420-5174-4fba-b204-15ff00192628.png)
![image](https://user-images.githubusercontent.com/107788214/194047959-49f90877-f80f-4195-8b77-eb1db087a579.png)
![image](https://user-images.githubusercontent.com/107788214/194048033-27952b7d-25b3-4517-8ac7-66445d5a764b.png)
