### ISSUE TITLE
Project Statuses: if there is no Baseline set, the status will be No Baseline always and what is mentioned in Config Manual is wrong, needs explanation and confirmation

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#55]
can you please advise or explain the highlighted below? 
if there is no Baseline set, the status will be No Baseline always, even if there is a task with no baseline, right? 

![image](https://user-images.githubusercontent.com/110157969/193786249-68ac2614-6593-4fcc-9465-8ba12a516706.png)

kindly check the below scenario, there is one task starting in 5/10 with no baseline, thus the status "No Baseline", and will not be "Not Started" right? This means that what is implemented is correct and the Config Manual is wrong, please confirm. 

![image](https://user-images.githubusercontent.com/110157969/193790399-9d79b50b-3622-4236-bbbb-62cdc6a886dd.png)

![image](https://user-images.githubusercontent.com/110157969/193790455-0b8f4777-3c9b-4318-8be5-7c772d229d55.png)

**Comment by KhaldounAl-haj** [comment]
@DemaHamideh we will remove the highlighted note from the manual you are right

**Comment by DemaHamideh** [comment]
will be checked in the updated configuration manual

**Comment by DemaHamideh** [comment]
Pass 

![image](https://user-images.githubusercontent.com/110157969/194748207-5ab64a43-a31c-45e7-be20-655d9e6c4894.png)
