### ISSUE TITLE
initiative card: Budget value adjustment

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Riyadh_Municipality_PPlus#59]
actual result: 
![image](https://user-images.githubusercontent.com/107788214/194232857-732b1f6a-e983-4544-8621-d1bbf942f7c2.png)

expected result: 

Budget value adjustment
“ألاف” instead of “ألف”

The value should be logical with the number
ألاف 5  
12 ألف

**Comment by tareqissa** [comment]
hello @hebaabutaha @ealtiti @JarrarMo @saqratieh 
this can't be done for all cases, millions of possibilities can occur so we need to make it as standard word for all possibilities, let's close this please.
