### ISSUE TITLE
Create New Project: after the request is submitted, an indicator should be shown to the user until finishing the submit process

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#6]
Steps:

1. login as PMO or Admin user (dhamideh/D@12345)
2. click on create new project 
3. fill fields then click on submit 

Actual Result: 
the user will be able to see the fields and edit them "also it will not be edited on EPM" and the system will take a while to show the success message 

https://user-images.githubusercontent.com/110157969/193448114-e367af29-311a-4d54-a159-94301108b2f5.mp4

Expected Result: 
loading page should be shown as an indicator to the user until finishing the submit process, or the fields should be disabled

**Comment by JarrarMo** [comment]
This is default behavior in PPlus in Creating Project.

@tareqissa , @HamzehJaddo kindly advise.

**Comment by tareqissa** [comment]
hello @JarrarMo @DemaHamideh 
My opinion is to go with the default implementation unless something specific is written in BRD
@HamzehJaddo your input please

**Comment by JarrarMo** [comment]
@DemaHamideh kindly remove bug label and make it as enhancement.

@saqratieh

**Comment by tareqissa** [comment]
@JarrarMo I didn't notice the video when I commented before, but now when I watched it, I think it's better to show the indicator as suggested for better user experience.

**Comment by JarrarMo** [comment]
@ealtiti if this needs a special design or something kindly inform me or @tareqissa

**Comment by ealtiti** [comment]
<img width="1432" alt="Screen Shot 2022-10-27 at 10 47 04 AM" src="https://user-images.githubusercontent.com/85454412/198222637-3a76d6ea-4be3-42d2-95f4-a2cdd9f3dd19.png">

**Comment by DemaHamideh** [comment]
Closed
