### ISSUE TITLE
Transfer risk to issue is not working 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#61]
Steps: 

1. login as epmadmin 
2. open an active risk http://rmpplus-qc.masterteam.sa/#/project/41cf33d6-8ebb-4008-bc8b-b4c03ee9f9c7/risks/details/2
3. click on transfer to an issue 

Actual Result: 
nothing happened and still active risk

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/200183131-32e7167e-0c7c-49fe-9a39-93c8bb598995.png)

**Comment by DemaHamideh** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/110157969/200243230-ea13338f-5981-4cff-be52-35285459be77.png)
