### ISSUE TITLE
QC - Task Center - Projects Tasks Approval: Expected Date shown as NA

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#64]
Steps: 

1. login as htaha//H@123456
2. go to task center and check Projects Tasks Approval
3. check task1

Actual Result: 
Expected Date shown as NA but it should be 30-09-2022

http://rmpplus-qc.masterteam.sa/#/project/a4c99f6b-4ab1-489c-8793-23b11e49f93c/tasks/

![image](https://user-images.githubusercontent.com/110157969/201513668-5346c028-5da5-4b97-9584-5015b415aaef.png)

![image](https://user-images.githubusercontent.com/110157969/201513682-6c436086-ca17-4319-9f84-e834637b149b.png)

**Comment by DemaHamideh** [comment]
related to bug #24

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/201515372-9cb5b7b2-5bba-4981-bd07-5ec7ca79078c.png)
![image](https://user-images.githubusercontent.com/53216161/201515384-95ad9383-d78e-4b07-86e1-1329ecfedb86.png)
