### ISSUE TITLE
QC - Project Workspace - Risks & Issues Tab: An error ocure when Project Owner or Sponsor try to add/edit a risk/issue 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#65]
Steps: 

1. login as test2/Master@123
2. open http://rmpplus-qc.masterteam.sa/#/project/a4c99f6b-4ab1-489c-8793-23b11e49f93c/issues
3. test 2 is the project owner 
4. click on add and fill the data
5. click on save 

Actual Result: 

![image](https://user-images.githubusercontent.com/110157969/201516288-baa3229b-3b00-47ec-879a-26e170811d8f.png)

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/201517033-3baaf4fa-0ba3-4743-819e-bf8e40649c3c.png)
![image](https://user-images.githubusercontent.com/53216161/201517059-841e8652-9f92-4666-a1ec-f696c4b1b52d.png)

**Comment by DemaHamideh** [comment]
Fixed
