### ISSUE TITLE
QC - Task Center - Phase Approvals: the request is not shown in this page when the user role is Admin only (works fine when the role is PMO)

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#68]
Steps: 

1. login as epmadmin as admin and htaha/H@123456 as PMO
2. go to task center and check Phase approvals section 
3. there is a request for D777 project 

Actual Result: 
for PMO user "htaha" it appears successfully, but for epmadmin "Admin" nothing appear although he is able to approve/reject it from the project workspace 

PMO user 

![image](https://user-images.githubusercontent.com/110157969/201520452-48821010-4e5c-4d8e-916b-1a991cca3f99.png)

Admin user 

![image](https://user-images.githubusercontent.com/110157969/201520386-21fa59eb-c489-48c0-9585-fdfd38fe0ba7.png)

![image](https://user-images.githubusercontent.com/110157969/201520419-bea8daf8-a184-4864-8391-09509f2147e4.png)

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/201528280-035a41db-b82b-4378-af06-4d2270a3d3eb.png)

**Comment by DemaHamideh** [comment]
Fixed
