### ISSUE TITLE
QC - Initiative Card - Project By Phases: cancelled should not be counted as per the CM

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#69]
![image](https://user-images.githubusercontent.com/110157969/201534417-86cae455-0e53-4f06-be8d-ab43eb18ae27.png)

CM 

![image](https://user-images.githubusercontent.com/110157969/201534437-723a80a6-cf88-4fa7-b959-aaf80a4ff627.png)

**Comment by JarrarMo** [comment]
@tareqissa this needs FE
