### ISSUE TITLE
Create New Project: some special character should be also not allowed to be typed 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#7]
Steps:

1. login as PMO or Admin user (dhamideh/D@12345)
2. click on create new project 
3. fill poject name as "dema //////"
4. fill fields then click on submit 

Actual Result: 
success message will appear but the porject will not be added to epm 

https://user-images.githubusercontent.com/110157969/193448475-7bd44490-a9bd-4764-8514-3314078b3e61.mp4

Expected Result: 
///// is special character should be also not allowed to be typed

**Comment by JarrarMo** [comment]
@ealtiti please ensure special characters contains all of the below

 .(period) \ " / : ; | ? ' < > * # ~ % & { } +

**Comment by DemaHamideh** [comment]
still accept 

\
_  (Underscore)
`
 [ 
 ]



![image](https://user-images.githubusercontent.com/110157969/193831757-4be951a1-a178-4efd-bae1-b1eaddacf528.png)

**Comment by DemaHamideh** [comment]
Pass
