### ISSUE TITLE
QC - Notifications: when the optional field "Project name in English && non project tasks title in English" is empty, the notification must show the mandatory filled value instead of null 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#70]
![image](https://user-images.githubusercontent.com/110157969/201642855-37e7ba5f-1ca0-43f1-b1a6-e09e8262dbfc.png)

![image](https://user-images.githubusercontent.com/110157969/201642945-042976d1-dfef-43b6-9671-1a2966b333ba.png)

![1](https://user-images.githubusercontent.com/110157969/201642987-1151643f-6dd6-44f4-9969-8a27c602d84d.png)

**Comment by JarrarMo** [comment]
@DemaHamideh kindly remove bug label, notifications were not part of the current scope.
