### ISSUE TITLE
Creating project under initiative that generated from S+ will not be linked with this initiative in epm and its program will be empty on epm

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#79]
Steps: 

1. add initiative from S+ 

![image](https://user-images.githubusercontent.com/110157969/203800231-70f1b654-606d-4b3e-9c70-a2429be6a259.png)

2. in P+, a add new project under the added initiative 

![image](https://user-images.githubusercontent.com/110157969/203800370-efdc020c-c6c3-4a37-ba7f-1df755eaaebb.png)

3. open the epm for the added project 

Actual Result: 
the project program "initiative" will be empty

![image](https://user-images.githubusercontent.com/110157969/203800935-345c2e99-2f9a-4a7d-b21a-d32b943c7c64.png)

Expected Result: 
this happened because the user who add the initiative in S+ didn't add the initiative name to the programs lookup

**Comment by JarrarMo** [comment]
@DemaHamideh adding new program to lookup is done, also delete program and update program name will update the lookup accordingly.
I will deploy it after training is done enshalla.

**Comment by JarrarMo** [comment]
@DemaHamideh kindly note for this to work, "Program Lookup (L2)" should be checked in all the time.

**Comment by DemaHamideh** [comment]
Fixed 
the initiative will be added to the program lookup and projects under it will be linked successfully 

![image](https://user-images.githubusercontent.com/110157969/204128988-751dffff-8bd6-4aa4-b66f-74508c29d8ff.png)

![image](https://user-images.githubusercontent.com/110157969/204128991-907c6e5d-81b8-4f5e-85e9-fd7b8f9cbdbf.png)
