### ISSUE TITLE
Project Card: the text الميزانية should be الميزانية الاجمالية as per the BRD 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#8]
Steps:

1. login as epmadmin
2. click on any initiative then click on any project to check project card 

Actual Result: 
the text الميزانية should be الميزانية الاجمالية as per the BRD 

![image](https://user-images.githubusercontent.com/110157969/193449179-52c34406-d17b-4a48-986b-2471101131c9.png)

**Comment by JarrarMo** [comment]
@KhaldounAl-haj kindly confirm the latest approved naming.

**Comment by KhaldounAl-haj** [comment]
The latest approved naming is "Budget" "الميزانية الإجمالية"  as per the latest BRD the screen shot provided is wrong

**Comment by JarrarMo** [comment]
@ealtiti kindly compare to latest design.

**Comment by ealtiti** [comment]
@JarrarMo  Done but this not  a FE Bug cus BRD is changing many times

**Comment by DemaHamideh** [comment]
Pass

![image](https://user-images.githubusercontent.com/110157969/193841581-d76c5981-b38f-4703-ae16-48fbfa2b55c7.png)
