### ISSUE TITLE
Email notitfication : Fix the email title when adding new project 

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#80]
Actual : ![image](https://github.com/user-attachments/assets/14339e66-c592-4d8d-ab88-e78ccdb52fcf)

Expected: 
![image](https://github.com/user-attachments/assets/9118cc6a-fd2a-4350-a93f-c9a99d7a7d66)

**Comment by nadeemyaldani** [comment]
This will be returned until we receive an Email design 
![image](https://github.com/user-attachments/assets/19d44534-5092-4c11-8f83-a59ccb97cf91)

**Comment by JarrarMo** [comment]
dear @tareqissa , this column in brd is the event not the email subject, this is the point we discussed by phone.

**Comment by tareqissa** [comment]
@nadeemyaldani @JarrarMo 
please let make new Subject as ("تحديد وزن مشروع "اسم المشروع)
@rhamad4 
please make this as business documentation not as bug since the email subject is not mentioned in the BRD

**Comment by nadeemyaldani** [comment]
![image](https://github.com/user-attachments/assets/821ec932-b4fa-4ebb-b836-fca0b3df3227)

**Comment by rhamad4** [comment]
fixed
