### ISSUE TITLE
Deliverables tab on project workspace  : Planned Progress % value is wrong

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#86]
Baseline start date = 01-07-2024

Baselin finish date = 15-07-2024

Planned = (30/06 - 01-07) / (15-07 -01-07) = (2/10 ) * 100% =20%

Actual: 100%
Expected: 20%

![image](https://github.com/user-attachments/assets/975ee616-fff0-4c4d-9fad-3dd9e8732fa5)

http://rmpplus-qc.masterteam.sa/#/project/3e820b6c-9930-4705-9b98-7b0581231c4a/deliverables

**Comment by nadeemyaldani** [comment]
When finish Date is less that Today it will be 100 
![image](https://github.com/user-attachments/assets/7eb13432-345e-4aae-b053-fdddbe2b9b09)

**Comment by JarrarMo** [comment]
@rhamad4 is it clear or still an issue?

**Comment by tareqissa** [comment]
@nadeemyaldani @rhamad4 @JarrarMo 
what is implemented is more logic which is the following:
if Baseline Finish Date < Today date --> Planned Progress = 100%

if Baseline Start Date > Today date --> Planned Progress = 0%

Other than that, we need to apply the formula as per the BRD to calculate the planned progress
