### ISSUE TITLE
Deliverables tab on project workspace : Deliverable status should be 100 if the actual = 100 ( set baseline is not a condition here )

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#88]
Pre condition : 
1.Add new deliverable with no baseline start and finish dates
2.make the actual progress = 100

Actual: ![image](https://github.com/user-attachments/assets/bf2660e6-63a1-4ffe-a7f9-85c033da1ead)
Expected: 
![image](https://github.com/user-attachments/assets/150b1bf8-f941-4c91-8d0f-fc6161569fbf)

http://rmpplus-qc.masterteam.sa/#/project/3e820b6c-9930-4705-9b98-7b0581231c4a/deliverables

**Comment by nadeemyaldani** [comment]
![image](https://github.com/user-attachments/assets/525aa9a5-1e0a-4aae-8245-04e5d083f976)

**Comment by rhamad4** [comment]
![image](https://github.com/user-attachments/assets/442775c7-20c1-4d48-92d4-18b100163071)
fixed
