### ISSUE TITLE
Project Card: Last update time is not correct 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#9]
Steps:

1. login as epmadmin
2. click on ديمة تيست initiative then click on "last update time test" to check the project card 
3. check Last Update value 

Actual Result: 
the last update is 3 hours ago while this project created 10 minutes before 

![image](https://user-images.githubusercontent.com/110157969/193449537-cf0b324c-5a99-496f-85d0-80c67a4ec8b9.png)

**Comment by JarrarMo** [comment]
Fixed, thank you.
![image](https://user-images.githubusercontent.com/53216161/193574481-7742fd5d-81e0-4448-820b-197cf3e585b5.png)
![image](https://user-images.githubusercontent.com/53216161/193574525-b9198125-09a6-426b-8979-ea1da8106388.png)

**Comment by DemaHamideh** [comment]
Pass 

![image](https://user-images.githubusercontent.com/110157969/193765504-93ec55a4-742a-466a-bf95-52f56fa16588.png)


![image](https://user-images.githubusercontent.com/110157969/193765537-48f12efd-c3a6-4224-87bf-3ec3d4151ec4.png)

**Comment by DemaHamideh** [comment]
Pass 

![image](https://user-images.githubusercontent.com/110157969/193765504-93ec55a4-742a-466a-bf95-52f56fa16588.png)


![image](https://user-images.githubusercontent.com/110157969/193765537-48f12efd-c3a6-4224-87bf-3ec3d4151ec4.png)
