### ISSUE TITLE
Project edit feature: The system display wrong confirmation message once the user submit the request

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#97]
Steps: 
1.Login using project manager
2.Navigate to project overview page
3.Click on edit button
4.Fill all required fields
5.Click on save button

Actual: 
![image](https://github.com/user-attachments/assets/0f5d83ef-f7d5-46fe-b6ea-1450c0c4588d)

Expected: 
![image](https://github.com/user-attachments/assets/89f49d87-b3fd-48c7-a9c4-a635f6c3e219)

**Comment by JarrarMo** [comment]
@tareqissa kindly provide English Translation

**Comment by tareqissa** [comment]
@nadeemyaldani @JarrarMo 
please let's use this translation "Project Data Update Process has been Created Successfully"

**Comment by rhamad4** [comment]
![image](https://github.com/user-attachments/assets/bb0e0219-693d-4b38-bb3a-398cfe2a776d)
fixed
