### ISSUE TITLE
Project Edit feature : system does not display the action history of the request page

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Riyadh_Municipality_PPlus#99]
Steps: 
1.Login using project manager
2.Navigate to project Processes page
3.Click on the process name
4.Observe the screen

![image](https://github.com/user-attachments/assets/c54f7441-2f3d-41ea-bd4e-4b11ae801900)
![image](https://github.com/user-attachments/assets/b3a73ca7-c0a2-47ea-98c7-50c0ce981b97)
http://rmpplus-qc.masterteam.sa/#/processes/updateproject/5395

**Comment by nadeemyaldani** [comment]
![image](https://github.com/user-attachments/assets/7a4967cb-2e78-4243-a914-e60e0a0bb22e)

**Comment by nadeemyaldani** [comment]
@SamerElaila

**Comment by tareqissa** [comment]
@nadeemyaldani @JarrarMo 
as agreed, the Waiting Duration is the different between the received date of the request and today date, the counter will stop until the action is taken.

**Comment by rhamad4** [comment]
![image](https://github.com/user-attachments/assets/ae04e0a8-ccc4-4c4e-957e-ff3aa0242cd2)
fixed
